### PR TITLE
make it link on mirage

### PR DESCRIPTION
**Pull request by cfcs**
Without these I get this:
```
_build/main.native.o: In function `camlSalsa20_core__salsa20_core_1281':
/home/user/.opam/4.04.2+fPIC/build/salsa20-core.0.3.0/_build/salsa20_core.ml:14: undefined reference to `caml_salsa_core'
_build/main.native.o: In function `camlSalsa20_core__6':
:(.data+0x7e2e0): undefined reference to `caml_salsa_core'
```

(Note: It still crashes MirageOS after a few seconds, but at least it can be compiled into a unikernel)

### CODE REVIEW

**Comment by abeaumont** [comment]
Thanks!

**Comment by cfcs** [comment]
BTW the crash turned out to be due to the exception thrown when the nonce is not of correct length -- seems to work fine on `mirage-xen`! :)

**Comment by hannesm** [comment]
sorry to disappoint you, but this solution is only partial.  in order to run C code on MirageOS in xen or kvm, it runs in ring 0 -- which does not have a red zone etc.  -- thus it needs to be (kind of cross-) compiled with specific cflags to work.  take a look into how nocrypto does it if you like (by using myocamlbuild.ml, some magic in pkg/pkg.ml, and ocl_stubblr).

**Comment by abeaumont** [comment]
There's already `myocamlbuild.ml` and `ocb_stubblr`, so I guess only some magic in `pkg/pkg.ml` may be missing.

**Comment by cfcs** [comment]
It works on `mirage-xen` for me (can initiate, encrypt, decrypt).

**Pull request merged**
